import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainFooter from "./components/footer";
import BikeHeader from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bike Junction Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BikeHeader />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
